name: Chroma Server for Vector DB
description: |
  Host a Chroma Server for Vector DB and Semantic Search, accessible via REST API

author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2023-11-02"

environment_variables:
  NAMESPACE:
    default: "cml-default"
    description: "Enter preferred namespace for Chroma DB to store document embeddings in."
    required: true

runtimes:
  - editor: JupyterLab
    kernel: Python 3.9
    edition: Standard

tasks:
  - type: run_session
    name: Install Dependencies
    script: 0_session-install-dependencies/download_requirements.py
    short_summary: Install Package Dependencies
    kernel: python3
    cpu: 2
    memory: 8
    
  # - type: create_job
  #   name: Populate Milvus Vector DB with documents embeddings
  #   entity_label: milvus_vectordb_insert
  #   script: 2_job-populate-vectordb/milvus_vectordb_insert.py
  #   arguments: None
  #   short_summary: Create job to populate Milvus Vector Database with document embeddings. (This is the default Vector DB and will run if "MILVUS" was left or set as the Vector DB.)
  #   long_summary: Create job to launch Milvus Vector Database locally and insert embeddings for documents. Embeddings are generated by the locally running embeddings model.
  #   cpu: 2
  #   memory: 8
  #   environment:
  #     TASK_TYPE: CREATE/RUN_JOB

  # - type: run_job
  #   entity_label: milvus_vectordb_insert
  #   short_summary: Populate Milvus Vector DB with documents embeddings

  - type: start_application
    name: CML Chroma Server REST API Server
    subdomain: cml-chroma-server
    script: 1_app/api_app.py
    short_summary: Create and start Chroma Server
    long_summary: Create and start Chroma Server REST API application. Vector Database creates encodings for GET and POST requests. Remember to enable unauthenticated app access for external access to the UI.
    cpu: 2
    memory: 8
    environment_variables:
      TASK_TYPE: START_APPLICATION
